/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as PostsImport } from "./routes/Posts";
import { Route as PostImport } from "./components/PostComponent/Post";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const PostsRoute = PostsImport.update({
	id: "/Posts",
	path: "/Posts",
	getParentRoute: () => rootRoute,
} as any);

const PostRoute = PostImport.update({
	id: "/Post",
	path: "/Post",
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/Post": {
			id: "/Post";
			path: "/Post";
			fullPath: "/Post";
			preLoaderRoute: typeof PostImport;
			parentRoute: typeof rootRoute;
		};
		"/Posts": {
			id: "/Posts";
			path: "/Posts";
			fullPath: "/Posts";
			preLoaderRoute: typeof PostsImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/Post": typeof PostRoute;
	"/Posts": typeof PostsRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/Post": typeof PostRoute;
	"/Posts": typeof PostsRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexRoute;
	"/Post": typeof PostRoute;
	"/Posts": typeof PostsRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/Post" | "/Posts";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/Post" | "/Posts";
	id: "__root__" | "/" | "/Post" | "/Posts";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	PostRoute: typeof PostRoute;
	PostsRoute: typeof PostsRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	PostRoute: PostRoute,
	PostsRoute: PostsRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Post",
        "/Posts"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Post": {
      "filePath": "Post.tsx"
    },
    "/Posts": {
      "filePath": "Posts.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
